import React, { useState, useEffect } from 'react';
import { api } from '../../../api';
import { orderService } from '../services/OrderService';
import { billingService } from '../../billing/services/BillingService';
import { SetState } from '../../../types';
import { MenuItem } from '../../menu/types/menu.types';
import { Order, OrderItem, OrderStatus } from '../types/order.types';
import Modal from '../../../components/ui/Modal';
import { PlusIcon, EditIcon, TrashIcon, SearchIcon, MinusIcon, ClipboardListIcon, PrinterIcon } from '../../../components/ui/Icons';
import { OrderNumberGenerator } from '../utils/orderNumberGenerator';
import { useRestaurantConfig } from '../../../contexts/RestaurantConfigContext';
import { generateAccessKey } from '../../billing/utils/sri';
import { generateInvoiceHtml } from '../../billing/utils/invoiceGenerator';
import InvoiceProcessingModal, { InvoiceProcessState } from '../../billing/components/InvoiceProcessingModal';

interface OrderManagementProps {
    orders: Order[];
    setOrders: SetState<Order[]>;
    menuItems: MenuItem[];
}

const inputClass = "w-full rounded-lg border border-gray-200 bg-gray-50 p-2.5 text-gray-900 text-sm focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:outline-none transition-all dark:border-gray-600 dark:bg-gray-700/50 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:bg-gray-700 dark:focus:ring-blue-500/20";

import { OrderCard } from './OrderCard';
import { OrderFormModal } from './OrderFormModal';
import POSView from './POSView';

// --- Main Order Management Component ---
const OrderManagement: React.FC<OrderManagementProps> = ({ orders, setOrders, menuItems }) => {
    const { config, refreshConfig } = useRestaurantConfig();
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingOrder, setEditingOrder] = useState<Order | null>(null);
    const [activeTab, setActiveTab] = useState<'active' | 'history'>('active');
    const [viewMode, setViewMode] = useState<'dashboard' | 'pos'>('dashboard');

    const handleOpenModal = (order: Order | null) => {
        setEditingOrder(order);
        setViewMode('pos');
    };

    const handleCloseModal = () => {
        setEditingOrder(null);
        setIsModalOpen(false);
    };

    const handleSaveOrder = async (orderToSave: Order) => {
        try {
            const exists = orders.some(o => o.id === orderToSave.id);
            if (exists) {
                const updated = await orderService.update(orderToSave.id, orderToSave);
                setOrders(prevOrders => prevOrders.map(o => o.id === orderToSave.id ? updated : o));
            } else {
                // Remove the temporary ID generated by the form if needed,
                // but the backend usually ignores validation of ID on create or overwrites it.
                // We'll send it as is, but rely on the returned object which has the real DB ID.
                const orderWithNumber = {
                    ...orderToSave,
                    orderNumber: orderToSave.orderNumber || OrderNumberGenerator.getNextOrderNumber()
                };
                const created = await orderService.create(orderWithNumber);

                // If the backend returns 'created' without orderNumber (mock usage usually returns what we sent, but just in case)
                // we ensure the local state has it.
                if (!created.orderNumber) created.orderNumber = orderWithNumber.orderNumber;

                setOrders(prevOrders => [...prevOrders, created]);
            }
        } catch (error) {
            console.error('Failed to save order:', error);
            alert('Error al guardar el pedido. Intente nuevamente.');
        }
    };

    const handleDeleteOrder = async (orderId: string) => {
        if (window.confirm('¿Seguro que quieres eliminar este pedido?')) {
            try {
                await orderService.delete(orderId);
                setOrders(prev => prev.filter(o => o.id !== orderId));
            } catch (error) {
                console.error('Failed to delete order:', error);
                alert('Error al eliminar el pedido.');
            }
        }
    };

    const handleStatusChange = async (orderId: string, newStatus: OrderStatus) => {
        try {
            const updated = await orderService.update(orderId, { status: newStatus });
            setOrders(prev => prev.map(o => o.id === orderId ? updated : o));
        } catch (error) {
            console.error('Failed to update status:', error);
            alert('Error al actualizar el estado.');
        }
    };

    const [isBillingModalOpen, setIsBillingModalOpen] = useState(false);
    const [billingOrder, setBillingOrder] = useState<Order | null>(null);
    const [billingData, setBillingData] = useState({
        identification: '',
        name: '',
        email: '',
        address: '',
        phone: '',
        paymentMethod: '01' // 01 - SIN UTILIZACION DEL SISTEMA FINANCIERO
    });

    // Estados para la búsqueda local de clientes
    const [searchingIdentity, setSearchingIdentity] = useState(false);
    const [lookupError, setLookupError] = useState<string | null>(null);

    // Estados para el modal de procesamiento de facturas
    const [isProcessingModalOpen, setIsProcessingModalOpen] = useState(false);
    const [processingState, setProcessingState] = useState<InvoiceProcessState>(InvoiceProcessState.IDLE);
    const [processingMessage, setProcessingMessage] = useState('');
    const [processingDetails, setProcessingDetails] = useState('');
    const [generatedInvoiceNumber, setGeneratedInvoiceNumber] = useState('');
    const [tempAccessKey, setTempAccessKey] = useState<string | undefined>();
    const [tempAuthDate, setTempAuthDate] = useState<string | undefined>();

    const handleOpenBilling = (order: Order) => {
        setBillingOrder(order);
        setBillingData({
            identification: '',
            name: order.customerName,
            email: '',
            address: '',
            phone: '',
            paymentMethod: '01'
        });
        setIsBillingModalOpen(true);
        setLookupError(null);
    };

    // Efecto para búsqueda automática de cliente por identificación
    useEffect(() => {
        const ident = billingData.identification;
        if (ident.length >= 10 && ident !== '9999999999999') {
            const timeoutId = setTimeout(async () => {
                setSearchingIdentity(true);
                setLookupError(null);
                try {
                    const customer = await api.customers.lookupByIdentification(ident);
                    if (customer) {
                        setBillingData(prev => ({
                            ...prev,
                            name: customer.name || prev.name,
                            email: customer.email || prev.email,
                            address: customer.address || prev.address,
                            phone: customer.phone || prev.phone
                        }));
                    }
                } catch (error: any) {
                    console.log('Customer not found in local DB or error:', error.message);
                    // Silently fail if not found, let user fill manually
                } finally {
                    setSearchingIdentity(false);
                }
            }, 600); // 600ms debounce
            return () => clearTimeout(timeoutId);
        }
    }, [billingData.identification]);

    const handleProcessBilling = async () => {
        // Email is now optional - validate only identification and name
        if (!billingData.identification || !billingData.name) {
            alert('Por favor complete RUC/Cédula y Nombre del cliente.');
            return;
        }

        // Warn if no email is provided (but allow to continue)
        const hasValidEmail = billingData.email &&
            billingData.email.includes('@') &&
            !billingData.email.includes('noemail');

        if (!hasValidEmail && billingData.identification !== '9999999999999') {
            const shouldContinue = window.confirm(
                '⚠️ No se ha ingresado un email válido.\n\n' +
                'La factura se generará correctamente pero NO se enviará por correo electrónico.\n' +
                'Podrás imprimir el PDF para entregarlo físicamente al cliente.\n\n' +
                '¿Deseas continuar sin email?'
            );
            if (!shouldContinue) return;
        }

        // Cerrar modal de billing y abrir modal de procesamiento
        setIsBillingModalOpen(false);
        setIsProcessingModalOpen(true);

        try {
            // ETAPA 1: Validación
            setProcessingState(InvoiceProcessState.VALIDATING);
            setProcessingMessage('Validando datos');
            setProcessingDetails('Verificando información del cliente y productos...');
            await new Promise(resolve => setTimeout(resolve, 500));

            // ETAPA 2: Generación
            setProcessingState(InvoiceProcessState.GENERATING);
            setProcessingMessage('Generando factura electrónica');
            setProcessingDetails('Creando documento XML según normativa SRI...');
            await new Promise(resolve => setTimeout(resolve, 800));

            // ETAPA 3: Firmado
            setProcessingState(InvoiceProcessState.SIGNING);
            setProcessingMessage('Firmando documento');
            setProcessingDetails('Aplicando certificado digital...');
            await new Promise(resolve => setTimeout(resolve, 600));

            // ETAPA 4: Enviando al SRI
            setProcessingState(InvoiceProcessState.SENDING);
            setProcessingMessage('Enviando al SRI');
            setProcessingDetails('Transmitiendo factura para recepción...');

            // Llamada real al backend
            console.log('Enviando a facturar:', { order: billingOrder, client: billingData });
            const result = await billingService.generateXML({
                order: billingOrder,
                client: billingData,
                taxRate: config.billing?.taxRate || 15,
                logoUrl: config.fiscalLogo || config.logo
            });

            if (result.success) {
                // ETAPA 5: Esperando autorización
                setProcessingState(InvoiceProcessState.WAITING_AUTHORIZATION);
                setProcessingMessage('Esperando autorización SRI');
                setProcessingDetails('El SRI está procesando la autorización...');
                await new Promise(resolve => setTimeout(resolve, 1000));

                const realAccessKey = result.accessKey;
                // CORRECCIÓN: El backend devuelve la autorización en result.authorization, no en sriResponse
                const authDate = result.authorization?.fechaAutorizacion || result.sriResponse?.fechaAutorizacion;
                const sriStatus = result.authorization?.estado || result.sriResponse?.estado;

                setTempAccessKey(realAccessKey);
                setTempAuthDate(authDate);
                setGeneratedInvoiceNumber(result.invoiceId);

                // Verificar si fue autorizada
                if (sriStatus === 'AUTORIZADO') {
                    // ÉXITO TOTAL
                    setProcessingState(InvoiceProcessState.AUTHORIZED);
                    setProcessingMessage('¡Factura autorizada con éxito!');
                    setProcessingDetails('La factura fue generada, recibida y autorizada por el SRI.');
                } else {
                    // GENERADA PERO PENDIENTE DE AUTORIZACIÓN
                    setProcessingState(InvoiceProcessState.PENDING);
                    setProcessingMessage('Factura generada correctamente');
                    setProcessingDetails(
                        'La factura fue creada y enviada al SRI, pero aún está EN PROCESO de autorización. ' +
                        'Puedes verificar su estado en el Historial de Facturas.'
                    );
                }

                // Refresh config to update the sequence number for the next invoice
                await refreshConfig();
            } else {
                // Error en la generación
                setProcessingState(InvoiceProcessState.ERROR);
                setProcessingMessage('Error al generar la factura');
                setProcessingDetails(result.message || 'Hubo un problema al procesar la factura.');
            }
        } catch (error) {
            console.error('Billing error', error);
            setProcessingState(InvoiceProcessState.ERROR);
            setProcessingMessage('Error en el proceso');
            const errorMessage = error instanceof Error ? error.message : 'Error al procesar la factura con el servidor.';
            setProcessingDetails(errorMessage);
        }
    };

    const handlePrintInvoice = (accessKey?: string, authDate?: string) => {
        if (!billingOrder) return;

        const printWindow = window.open('', '_blank', 'width=800,height=600');
        if (!printWindow) {
            alert('Por favor permite ventanas emergentes para imprimir.');
            return;
        }

        const html = generateInvoiceHtml(billingOrder, config, billingData, accessKey, authDate);

        printWindow.document.write(html);
        printWindow.document.close();
    };

    const handleCloseProcessingModal = () => {
        setIsProcessingModalOpen(false);
        setProcessingState(InvoiceProcessState.IDLE);
        setProcessingMessage('');
        setProcessingDetails('');
        setGeneratedInvoiceNumber('');
        setTempAccessKey(undefined);
        setTempAuthDate(undefined);
    };

    const handlePrintFromProcessingModal = () => {
        handlePrintInvoice(tempAccessKey, tempAuthDate);
        handleCloseProcessingModal();
    };

    const handleGoToHistory = () => {
        // Aquí puedes agregar navegación al historial de facturas
        // Por ahora simplemente cerramos el modal y el usuario puede navegar manualmente
        handleCloseProcessingModal();
        alert('Por favor, dirígete a la sección "Historial de Facturas" para verificar el estado de la factura.');
    };

    const filteredOrders = (Array.isArray(orders) ? orders : []).filter(order => {
        if (activeTab === 'active') {
            return order.status === OrderStatus.New || order.status === OrderStatus.Ready;
        } else {
            return order.status === OrderStatus.Completed;
        }
    });


    return (
        <div className="flex flex-col h-full">
            {/* Common Header / Selector */}
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-8 gap-6">
                <div className="flex flex-col">
                    <h1 className="text-3xl font-black text-gray-900 dark:text-white uppercase tracking-tighter">Operaciones</h1>
                    <p className="text-xs font-bold text-blue-600 dark:text-blue-400 flex items-center gap-1">
                        <span className="w-2 h-2 rounded-full bg-blue-600 animate-pulse"></span>
                        CENTRAL DE CONTROL RESTAURANTE
                    </p>
                </div>

                <div className="flex items-center gap-4">
                    <div className="flex bg-gray-100 dark:bg-dark-800 p-1 rounded-xl shadow-inner border border-gray-200 dark:border-dark-700">
                        <button
                            onClick={() => { setViewMode('dashboard'); setEditingOrder(null); }}
                            className={`px-6 py-2 rounded-lg text-xs font-black transition-all ${viewMode === 'dashboard' ? 'bg-white dark:bg-dark-700 text-blue-600 dark:text-blue-400 shadow-md ring-1 ring-black/5' : 'text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'}`}
                        >
                            TABLERO
                        </button>
                        <button
                            onClick={() => setViewMode('pos')}
                            className={`px-6 py-2 rounded-lg text-xs font-black transition-all ${viewMode === 'pos' ? 'bg-white dark:bg-dark-700 text-blue-600 dark:text-blue-400 shadow-md ring-1 ring-black/5' : 'text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'}`}
                        >
                            SISTEMA POS
                        </button>
                    </div>

                    {viewMode === 'dashboard' && (
                        <>
                            <div className="h-8 w-[1px] bg-gray-200 dark:bg-dark-700 mx-2 hidden sm:block"></div>
                            <div className="flex bg-gray-100 dark:bg-dark-800 p-1 rounded-xl">
                                <button
                                    onClick={() => setActiveTab('active')}
                                    className={`px-4 py-2 rounded-lg text-xs font-bold transition-all ${activeTab === 'active' ? 'bg-white dark:bg-dark-700 text-blue-600 dark:text-blue-400 shadow-sm' : 'text-gray-400'}`}
                                >
                                    EN CURSO
                                </button>
                                <button
                                    onClick={() => setActiveTab('history')}
                                    className={`px-4 py-2 rounded-lg text-xs font-bold transition-all ${activeTab === 'history' ? 'bg-white dark:bg-dark-700 text-blue-600 dark:text-blue-400 shadow-sm' : 'text-gray-400'}`}
                                >
                                    HISTORIAL
                                </button>
                            </div>
                        </>
                    )}
                </div>

                {viewMode === 'dashboard' && (
                    <button 
                        onClick={() => handleOpenModal(null)} 
                        className="flex items-center bg-blue-600 text-white px-8 py-3 rounded-2xl font-black text-sm hover:bg-blue-700 transition-all shadow-xl shadow-blue-500/25 active:scale-95 group"
                    >
                        <PlusIcon className="w-5 h-5 mr-2 group-hover:rotate-90 transition-transform" /> 
                        NUEVO PEDIDO
                    </button>
                )}
            </div>

            {/* Content Rendering */}
            {viewMode === 'pos' ? (
                <POSView 
                    menuItems={menuItems} 
                    onSave={handleSaveOrder} 
                    onCancel={() => {
                        setViewMode('dashboard');
                        setEditingOrder(null);
                    }}
                    initialOrder={editingOrder}
                />
            ) : (
                <>
            {isBillingModalOpen && billingOrder && (
                <Modal isOpen={isBillingModalOpen} onClose={() => setIsBillingModalOpen(false)} title="Emitir Factura Electrónica (SRI)" maxWidth="max-w-4xl">
                    <div className="flex flex-col md:flex-row gap-6 p-2">
                        {/* Left Column: Invoice Preview (Visual Representation) */}
                        <div className="flex-1 bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 shadow-sm rounded-sm p-6 text-xs text-gray-800 dark:text-gray-300 font-mono relative overflow-hidden">
                            <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[100px] text-gray-100 dark:text-dark-800 -rotate-45 pointer-events-none font-sans font-bold opacity-50">
                                VISTA PREVIA
                            </div>

                            <div className="relative mb-6 flex justify-between items-start border-b border-gray-300 dark:border-dark-600 pb-4">
                                <div>
                                    {config.fiscalLogo || config.logo ? (
                                        <div className="mb-6 flex justify-center">
                                            <img
                                                src={config.fiscalLogo || config.logo}
                                                alt="Logo"
                                                className="max-w-[240px] max-h-[120px] w-auto h-auto object-contain rounded-lg"
                                            />
                                        </div>
                                    ) : (
                                        <div className="w-20 h-20 bg-gray-200 dark:bg-dark-700 rounded mb-4 flex items-center justify-center text-3xl mx-auto">🍽️</div>
                                    )}
                                    <h2 className="font-bold text-lg uppercase text-gray-900 dark:text-white leading-tight">{config.name || 'NOMBRE COMERCIAL'}</h2>
                                    <h3 className="text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase mb-1">{config.businessName || 'CLIENTE'}</h3>
                                    <p>{config.address || 'Dirección Matriz, Ciudad, Ecuador'}</p>
                                    <p>RUC: {config.ruc || '9999999999001'}</p>
                                    <p>{config.fiscalEmail || config.email || 'correo@ejemplo.com'}</p>
                                    <p>Obligado a llevar contabilidad: {config.obligadoContabilidad ? 'SI' : 'NO'}</p>
                                </div>
                                <div className="text-right">
                                    <h3 className="font-bold text-sm">FACTURA</h3>
                                    <p className="font-mono text-lg font-bold text-red-600 dark:text-red-400">No. {config.billing?.establishment || '001'}-{config.billing?.emissionPoint || '001'}-{((config.billing?.currentSequenceFactura || 0) + 1).toString().padStart(9, '0')}</p>
                                    <p><span className="font-bold">FECHA EMISIÓN:</span> {new Date().toLocaleDateString('es-EC')}</p>
                                </div>
                            </div>

                            <div className="relative mb-4 border border-gray-800 dark:border-gray-500 rounded p-3 bg-transparent text-[10px]">
                                <div className="grid grid-cols-2 gap-x-4 gap-y-1">
                                    <div><span className="font-bold">Cliente:</span> {billingData.name || 'ANÓNIMO'}</div>
                                    <div><span className="font-bold">RUC/CI:</span> {billingData.identification || '9999999999999'}</div>
                                    <div className="col-span-2"><span className="font-bold">Dirección:</span> {billingData.address || 'S/N'}</div>
                                </div>
                            </div>

                            <div className="relative">
                                <div className="border border-gray-200 dark:border-dark-700 rounded-sm overflow-hidden mb-4">
                                    <table className="w-full text-[10px]">
                                        <thead className="bg-gray-100 dark:bg-dark-800 text-left font-bold border-b border-gray-200 dark:border-dark-700">
                                            <tr>
                                                <th className="px-2 py-1">Cant</th>
                                                <th className="px-2 py-1">Descripción</th>
                                                <th className="px-2 py-1 text-right">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-gray-100 dark:divide-dark-800">
                                            {billingOrder.items.map((item, idx) => (
                                                <tr key={idx}>
                                                    <td className="px-2 py-1">{item.quantity}</td>
                                                    <td className="px-2 py-1">{item.name}</td>
                                                    <td className="px-2 py-1 text-right">${((item.price || 0) * item.quantity).toFixed(2)}</td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>
                                <div className="flex justify-end">
                                    <div className="w-1/2 border border-gray-200 dark:border-dark-700 rounded-sm">
                                        <table className="w-full text-[10px]">
                                            <tbody>
                                                <tr>
                                                    <td className="px-2 py-1 font-bold bg-gray-50 dark:bg-dark-800">TOTAL</td>
                                                    <td className="px-2 py-1 text-right font-bold">${billingOrder.items.reduce((s, i) => s + (i.price || 0) * i.quantity, 0).toFixed(2)}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Right Column: Client Data Form */}
                        <div className="md:w-1/3 space-y-4 border-l dark:border-dark-700 md:pl-6">
                            <h3 className="text-lg font-bold text-gray-900 dark:text-white">Datos del Cliente</h3>
                            <button
                                onClick={() => setBillingData({
                                    identification: '9999999999999',
                                    name: 'CONSUMIDOR FINAL',
                                    email: 'consumidor@final.com',
                                    address: 'S/N',
                                    phone: '9999999999',
                                    paymentMethod: '01'
                                })}
                                className="w-full py-1.5 bg-gray-100 hover:bg-gray-200 dark:bg-dark-700 dark:hover:bg-dark-600 text-xs font-semibold text-gray-600 dark:text-gray-300 rounded border border-gray-300 dark:border-dark-600 transition-colors"
                            >
                                Usar "Consumidor Final"
                            </button>

                            <div className="space-y-3">
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 mb-1 uppercase tracking-wider">Identificación</label>
                                    <input
                                        type="text"
                                        value={billingData.identification}
                                        onChange={e => setBillingData({ ...billingData, identification: e.target.value })}
                                        className={inputClass}
                                        placeholder="RUC / Cédula"
                                    />
                                    {searchingIdentity && <p className="text-[10px] text-blue-500 mt-1 animate-pulse">Buscando datos...</p>}
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 mb-1 uppercase tracking-wider">Nombre / Razón Social</label>
                                    <input
                                        type="text"
                                        value={billingData.name}
                                        onChange={e => setBillingData({ ...billingData, name: e.target.value.toUpperCase() })}
                                        className={inputClass}
                                        placeholder="Nombre del cliente"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 mb-1 uppercase tracking-wider">Email</label>
                                    <input
                                        type="email"
                                        value={billingData.email}
                                        onChange={e => setBillingData({ ...billingData, email: e.target.value })}
                                        className={inputClass}
                                        placeholder="cliente@email.com"
                                    />
                                </div>
                            </div>

                            <div className="pt-4 space-y-2">
                                <button
                                    onClick={handleProcessBilling}
                                    disabled={!billingData.identification || !billingData.name}
                                    className="w-full py-3 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 disabled:opacity-50 transition-all shadow-lg active:scale-95"
                                >
                                    Emitir Factura
                                </button>
                                <button
                                    onClick={() => setIsBillingModalOpen(false)}
                                    className="w-full py-2 text-gray-500 hover:text-gray-700 text-sm"
                                >
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                </Modal>
            )}
            <OrderFormModal isOpen={isModalOpen} onClose={handleCloseModal} onSave={handleSaveOrder} order={editingOrder} menuItems={menuItems} />

            {/* Invoice Processing Modal */}
            <InvoiceProcessingModal
                isOpen={isProcessingModalOpen}
                currentState={processingState}
                message={processingMessage}
                details={processingDetails}
                invoiceNumber={generatedInvoiceNumber}
                onClose={handleCloseProcessingModal}
                onPrint={handlePrintFromProcessingModal}
                onGoToHistory={handleGoToHistory}
            />

            {/* Billing Modal Integration */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 mt-8">
                {filteredOrders.length === 0 ? (
                    <div className="col-span-full text-center py-12 text-gray-500 dark:text-gray-400">
                        {activeTab === 'active' ? 'No hay pedidos en curso.' : 'No hay historial de pedidos completados.'}
                    </div>
                ) : (
                    filteredOrders
                        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
                        .map(order => (
                            <OrderCard
                                key={order.id}
                                order={order}
                                onEdit={() => handleOpenModal(order)}
                                onDelete={() => handleDeleteOrder(order.id)}
                                onStatusChange={(newStatus) => handleStatusChange(order.id, newStatus)}
                                onBilling={() => handleOpenBilling(order)}
                            />
                        ))
                )}
            </div>
                </>
            )}
        </div>
    );
};

export default OrderManagement;
