import React, { useState, useEffect } from 'react';
import { api } from '../../../api';
import { orderService } from '../services/OrderService';
import { billingService } from '../../billing/services/BillingService';
import { SetState } from '../../../types';
import { MenuItem } from '../../menu/types/menu.types';
import { Order, OrderItem, OrderStatus } from '../types/order.types';
import Modal from '../../../components/ui/Modal';
import { PlusIcon, EditIcon, TrashIcon, SearchIcon, MinusIcon, ClipboardListIcon, PrinterIcon } from '../../../components/ui/Icons';
import { OrderNumberGenerator } from '../utils/orderNumberGenerator';
import { useRestaurantConfig } from '../../../contexts/RestaurantConfigContext';
import { generateAccessKey } from '../../billing/utils/sri';
import { generateInvoiceHtml } from '../../billing/utils/invoiceGenerator';
import InvoiceProcessingModal, { InvoiceProcessState } from '../../billing/components/InvoiceProcessingModal';

interface OrderManagementProps {
    orders: Order[];
    setOrders: SetState<Order[]>;
    menuItems: MenuItem[];
}

const inputClass = "w-full rounded-lg border border-gray-200 bg-gray-50 p-2.5 text-gray-900 text-sm focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-500/20 focus:outline-none transition-all dark:border-gray-600 dark:bg-gray-700/50 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:bg-gray-700 dark:focus:ring-blue-500/20";

import { OrderCard } from './OrderCard';
import { OrderFormModal } from './OrderFormModal';

// --- Main Order Management Component ---
const OrderManagement: React.FC<OrderManagementProps> = ({ orders, setOrders, menuItems }) => {
    const { config, refreshConfig } = useRestaurantConfig();
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingOrder, setEditingOrder] = useState<Order | null>(null);
    const [activeTab, setActiveTab] = useState<'active' | 'history'>('active');

    const handleOpenModal = (order: Order | null) => {
        setEditingOrder(order);
        setIsModalOpen(true);
    };

    const handleCloseModal = () => {
        setEditingOrder(null);
        setIsModalOpen(false);
    };

    const handleSaveOrder = async (orderToSave: Order) => {
        try {
            const exists = orders.some(o => o.id === orderToSave.id);
            if (exists) {
                const updated = await orderService.update(orderToSave.id, orderToSave);
                setOrders(prevOrders => prevOrders.map(o => o.id === orderToSave.id ? updated : o));
            } else {
                // Remove the temporary ID generated by the form if needed,
                // but the backend usually ignores validation of ID on create or overwrites it.
                // We'll send it as is, but rely on the returned object which has the real DB ID.
                const orderWithNumber = {
                    ...orderToSave,
                    orderNumber: orderToSave.orderNumber || OrderNumberGenerator.getNextOrderNumber()
                };
                const created = await orderService.create(orderWithNumber);

                // If the backend returns 'created' without orderNumber (mock usage usually returns what we sent, but just in case)
                // we ensure the local state has it.
                if (!created.orderNumber) created.orderNumber = orderWithNumber.orderNumber;

                setOrders(prevOrders => [...prevOrders, created]);
            }
        } catch (error) {
            console.error('Failed to save order:', error);
            alert('Error al guardar el pedido. Intente nuevamente.');
        }
    };

    const handleDeleteOrder = async (orderId: string) => {
        if (window.confirm('¿Seguro que quieres eliminar este pedido?')) {
            try {
                await orderService.delete(orderId);
                setOrders(prev => prev.filter(o => o.id !== orderId));
            } catch (error) {
                console.error('Failed to delete order:', error);
                alert('Error al eliminar el pedido.');
            }
        }
    };

    const handleStatusChange = async (orderId: string, newStatus: OrderStatus) => {
        try {
            const updated = await orderService.update(orderId, { status: newStatus });
            setOrders(prev => prev.map(o => o.id === orderId ? updated : o));
        } catch (error) {
            console.error('Failed to update status:', error);
            alert('Error al actualizar el estado.');
        }
    };

    const [isBillingModalOpen, setIsBillingModalOpen] = useState(false);
    const [billingOrder, setBillingOrder] = useState<Order | null>(null);
    const [billingData, setBillingData] = useState({
        identification: '',
        name: '',
        email: '',
        address: '',
        phone: '',
        paymentMethod: '01' // 01 - SIN UTILIZACION DEL SISTEMA FINANCIERO
    });

    // Estados para el modal de procesamiento de facturas
    const [isProcessingModalOpen, setIsProcessingModalOpen] = useState(false);
    const [processingState, setProcessingState] = useState<InvoiceProcessState>(InvoiceProcessState.IDLE);
    const [processingMessage, setProcessingMessage] = useState('');
    const [processingDetails, setProcessingDetails] = useState('');
    const [generatedInvoiceNumber, setGeneratedInvoiceNumber] = useState('');
    const [tempAccessKey, setTempAccessKey] = useState<string | undefined>();
    const [tempAuthDate, setTempAuthDate] = useState<string | undefined>();

    const handleOpenBilling = (order: Order) => {
        setBillingOrder(order);
        // Pre-fill with available data from order or customer database (mocked here)
        setBillingData({
            identification: '', // In real app, fetch from customer profile
            name: order.customerName,
            email: '',
            address: '',
            phone: '',
            paymentMethod: '01'
        });
        setIsBillingModalOpen(true);
    };

    const handleProcessBilling = async () => {
        // Email is now optional - validate only identification and name
        if (!billingData.identification || !billingData.name) {
            alert('Por favor complete RUC/Cédula y Nombre del cliente.');
            return;
        }

        // Warn if no email is provided (but allow to continue)
        const hasValidEmail = billingData.email &&
            billingData.email.includes('@') &&
            !billingData.email.includes('noemail');

        if (!hasValidEmail && billingData.identification !== '9999999999999') {
            const shouldContinue = window.confirm(
                '⚠️ No se ha ingresado un email válido.\n\n' +
                'La factura se generará correctamente pero NO se enviará por correo electrónico.\n' +
                'Podrás imprimir el PDF para entregarlo físicamente al cliente.\n\n' +
                '¿Deseas continuar sin email?'
            );
            if (!shouldContinue) return;
        }

        // Cerrar modal de billing y abrir modal de procesamiento
        setIsBillingModalOpen(false);
        setIsProcessingModalOpen(true);

        try {
            // ETAPA 1: Validación
            setProcessingState(InvoiceProcessState.VALIDATING);
            setProcessingMessage('Validando datos');
            setProcessingDetails('Verificando información del cliente y productos...');
            await new Promise(resolve => setTimeout(resolve, 500));

            // ETAPA 2: Generación
            setProcessingState(InvoiceProcessState.GENERATING);
            setProcessingMessage('Generando factura electrónica');
            setProcessingDetails('Creando documento XML según normativa SRI...');
            await new Promise(resolve => setTimeout(resolve, 800));

            // ETAPA 3: Firmado
            setProcessingState(InvoiceProcessState.SIGNING);
            setProcessingMessage('Firmando documento');
            setProcessingDetails('Aplicando certificado digital...');
            await new Promise(resolve => setTimeout(resolve, 600));

            // ETAPA 4: Enviando al SRI
            setProcessingState(InvoiceProcessState.SENDING);
            setProcessingMessage('Enviando al SRI');
            setProcessingDetails('Transmitiendo factura para recepción...');

            // Llamada real al backend
            console.log('Enviando a facturar:', { order: billingOrder, client: billingData });
            const result = await billingService.generateXML({
                order: billingOrder,
                client: billingData,
                taxRate: config.billing?.taxRate || 15,
                logoUrl: config.fiscalLogo || config.logo
            });

            if (result.success) {
                // ETAPA 5: Esperando autorización
                setProcessingState(InvoiceProcessState.WAITING_AUTHORIZATION);
                setProcessingMessage('Esperando autorización SRI');
                setProcessingDetails('El SRI está procesando la autorización...');
                await new Promise(resolve => setTimeout(resolve, 1000));

                const realAccessKey = result.accessKey;
                // CORRECCIÓN: El backend devuelve la autorización en result.authorization, no en sriResponse
                const authDate = result.authorization?.fechaAutorizacion || result.sriResponse?.fechaAutorizacion;
                const sriStatus = result.authorization?.estado || result.sriResponse?.estado;

                setTempAccessKey(realAccessKey);
                setTempAuthDate(authDate);
                setGeneratedInvoiceNumber(result.invoiceId);

                // Verificar si fue autorizada
                if (sriStatus === 'AUTORIZADO') {
                    // ÉXITO TOTAL
                    setProcessingState(InvoiceProcessState.AUTHORIZED);
                    setProcessingMessage('¡Factura autorizada con éxito!');
                    setProcessingDetails('La factura fue generada, recibida y autorizada por el SRI.');
                } else {
                    // GENERADA PERO PENDIENTE DE AUTORIZACIÓN
                    setProcessingState(InvoiceProcessState.PENDING);
                    setProcessingMessage('Factura generada correctamente');
                    setProcessingDetails(
                        'La factura fue creada y enviada al SRI, pero aún está EN PROCESO de autorización. ' +
                        'Puedes verificar su estado en el Historial de Facturas.'
                    );
                }

                // Refresh config to update the sequence number for the next invoice
                await refreshConfig();
            } else {
                // Error en la generación
                setProcessingState(InvoiceProcessState.ERROR);
                setProcessingMessage('Error al generar la factura');
                setProcessingDetails(result.message || 'Hubo un problema al procesar la factura.');
            }
        } catch (error) {
            console.error('Billing error', error);
            setProcessingState(InvoiceProcessState.ERROR);
            setProcessingMessage('Error en el proceso');
            const errorMessage = error instanceof Error ? error.message : 'Error al procesar la factura con el servidor.';
            setProcessingDetails(errorMessage);
        }
    };

    const handlePrintInvoice = (accessKey?: string, authDate?: string) => {
        if (!billingOrder) return;

        const printWindow = window.open('', '_blank', 'width=800,height=600');
        if (!printWindow) {
            alert('Por favor permite ventanas emergentes para imprimir.');
            return;
        }

        const html = generateInvoiceHtml(billingOrder, config, billingData, accessKey, authDate);

        printWindow.document.write(html);
        printWindow.document.close();
    };

    const handleCloseProcessingModal = () => {
        setIsProcessingModalOpen(false);
        setProcessingState(InvoiceProcessState.IDLE);
        setProcessingMessage('');
        setProcessingDetails('');
        setGeneratedInvoiceNumber('');
        setTempAccessKey(undefined);
        setTempAuthDate(undefined);
    };

    const handlePrintFromProcessingModal = () => {
        handlePrintInvoice(tempAccessKey, tempAuthDate);
        handleCloseProcessingModal();
    };

    const handleGoToHistory = () => {
        // Aquí puedes agregar navegación al historial de facturas
        // Por ahora simplemente cerramos el modal y el usuario puede navegar manualmente
        handleCloseProcessingModal();
        alert('Por favor, dirígete a la sección "Historial de Facturas" para verificar el estado de la factura.');
    };

    const filteredOrders = (Array.isArray(orders) ? orders : []).filter(order => {
        if (activeTab === 'active') {
            return order.status === OrderStatus.New || order.status === OrderStatus.Ready;
        } else {
            return order.status === OrderStatus.Completed;
        }
    });



    return (
        <div>
            <OrderFormModal isOpen={isModalOpen} onClose={handleCloseModal} onSave={handleSaveOrder} order={editingOrder} menuItems={menuItems} />

            {/* Invoice Processing Modal */}
            <InvoiceProcessingModal
                isOpen={isProcessingModalOpen}
                currentState={processingState}
                message={processingMessage}
                details={processingDetails}
                invoiceNumber={generatedInvoiceNumber}
                onClose={handleCloseProcessingModal}
                onPrint={handlePrintFromProcessingModal}
                onGoToHistory={handleGoToHistory}
            />

            {/* Billing Modal Integration */}
            {isBillingModalOpen && billingOrder && (
                <Modal isOpen={isBillingModalOpen} onClose={() => setIsBillingModalOpen(false)} title="Emitir Factura Electrónica (SRI)" maxWidth="max-w-4xl">
                    <div className="flex flex-col md:flex-row gap-6 p-2">
                        {/* Left Column: Invoice Preview (Visual Representation) */}
                        {/* Invoice Preview Box */}
                        <div className="flex-1 bg-white dark:bg-dark-900 border border-gray-200 dark:border-dark-700 shadow-sm rounded-sm p-6 text-xs text-gray-800 dark:text-gray-300 font-mono relative overflow-hidden">
                            {/* Watermark/Background effect for Preview */}
                            <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-[100px] text-gray-100 dark:text-dark-800 -rotate-45 pointer-events-none font-sans font-bold opacity-50">
                                VISTA PREVIA
                            </div>

                            {/* Header Section */}
                            <div className="relative mb-6 flex justify-between items-start border-b border-gray-300 dark:border-dark-600 pb-4">
                                <div>
                                    {config.fiscalLogo || config.logo ? (
                                        <div className="mb-6 flex justify-center">
                                            <img
                                                src={config.fiscalLogo || config.logo}
                                                alt="Logo"
                                                className="max-w-[240px] max-h-[120px] w-auto h-auto object-contain rounded-lg"
                                            />
                                        </div>
                                    ) : (
                                        <div className="w-20 h-20 bg-gray-200 dark:bg-dark-700 rounded mb-4 flex items-center justify-center text-3xl mx-auto">🍽️</div>
                                    )}
                                    <h2 className="font-bold text-lg uppercase text-gray-900 dark:text-white leading-tight">{config.name || 'NOMBRE COMERCIAL'}</h2>
                                    <h3 className="text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase mb-1">{config.businessName || 'CLIENTE'}</h3>
                                    <p>{config.address || 'Dirección Matriz, Ciudad, Ecuador'}</p>
                                    <p>RUC: {config.ruc || '9999999999001'}</p>
                                    <p>{config.fiscalEmail || config.email || 'correo@ejemplo.com'}</p>
                                    {config.contribuyenteEspecial && (
                                        <p className="font-bold">Contribuyente Especial Nro: {config.contribuyenteEspecial}</p>
                                    )}
                                    <p>Obligado a llevar contabilidad: {config.obligadoContabilidad ? 'SI' : 'NO'}</p>
                                </div>
                                <div className="text-right">
                                    <h3 className="font-bold text-sm">FACTURA</h3>
                                    <p className="font-mono text-lg font-bold text-red-600 dark:text-red-400">No. {config.billing?.establishment || '001'}-{config.billing?.emissionPoint || '001'}-{((config.billing?.currentSequenceFactura || 0) + 1).toString().padStart(9, '0')}</p>
                                    <p><span className="font-bold">FECHA EMISIÓN:</span> {new Date().toLocaleDateString('es-EC')}</p>

                                    <div className="mt-2 flex flex-col items-end gap-1">
                                        <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-300 border border-green-200 dark:border-green-800">
                                            Ambiente: {config.billing?.environment === '2' ? 'PRODUCCIÓN' : 'PRUEBAS'}
                                        </span>
                                        <span className="px-2 py-0.5 rounded text-[10px] uppercase font-bold bg-blue-100 text-blue-800 dark:bg-blue-900/40 dark:text-blue-300 border border-blue-200 dark:border-blue-800">
                                            Emisión: NORMAL
                                        </span>
                                    </div>
                                </div>
                            </div>

                            {/* Client Section (Preview) */}
                            <div className="relative mb-4 border border-gray-800 dark:border-gray-500 rounded p-3 bg-transparent">

                                <div className="grid grid-cols-2 gap-x-4 gap-y-1">
                                    <div><span className="font-bold">Cliente:</span> {typeof billingData.name === 'string' ? billingData.name : JSON.stringify(billingData.name) || 'ANÓNIMO'}</div>
                                    <div><span className="font-bold max-w-[200px] truncate">RUC/CI:</span> {typeof billingData.identification === 'string' ? billingData.identification : String(billingData.identification || '9999999999999')}</div>
                                    <div><span className="font-bold">Fecha Emisión:</span> {new Date().toLocaleDateString('es-EC')}</div>
                                    <div className="col-span-2"><span className="font-bold">Dirección:</span> {typeof billingData.address === 'string' ? billingData.address : String(billingData.address || 'S/N')}</div>
                                    <div><span className="font-bold">Teléfono:</span> {typeof billingData.phone === 'string' ? billingData.phone : String(billingData.phone || 'S/N')}</div>
                                    <div className="flex flex-col">
                                        <span className="font-bold">Forma de Pago:</span>
                                        <span className="text-[10px] break-words">
                                            {String(billingData.paymentMethod) === '01' ? '01 - SIN UTILIZACION DEL SISTEMA FINANCIERO' :
                                                String(billingData.paymentMethod) === '20' ? '20 - OTROS CON UTILIZACION DEL SISTEMA FINANCIERO' :
                                                    String(billingData.paymentMethod) === '19' ? '19 - TARJETA DE CREDITO' :
                                                        '01 - SIN UTILIZACION DEL SISTEMA FINANCIERO'}
                                        </span>
                                    </div>
                                </div>
                            </div>

                            {/* Order Items Detail */}
                            <div className="relative">
                                <div className="border border-gray-200 dark:border-dark-700 rounded-sm overflow-hidden mb-4">
                                    <table className="w-full text-xs">
                                        <thead className="bg-gray-100 dark:bg-dark-800 text-left font-bold text-gray-700 dark:text-gray-300 border-b border-gray-200 dark:border-dark-700">
                                            <tr>
                                                <th className="px-2 py-1">Cant</th>
                                                <th className="px-2 py-1">Descripción</th>
                                                <th className="px-2 py-1 text-right">P. Unit</th>
                                                <th className="px-2 py-1 text-right">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-gray-100 dark:divide-dark-800">
                                            {billingOrder.items.map((item, idx) => (
                                                <tr key={idx} className="bg-white dark:bg-dark-900">
                                                    <td className="px-2 py-1">{item.quantity}</td>
                                                    <td className="px-2 py-1">{item.name}</td>
                                                    <td className="px-2 py-1 text-right">${(item.price || 0).toFixed(2)}</td>
                                                    <td className="px-2 py-1 text-right font-medium">
                                                        ${((item.price || 0) * item.quantity).toFixed(2)}
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                </div>

                                {/* Totals Block */}
                                <div className="flex justify-end">
                                    <div className="w-1/2 border border-gray-200 dark:border-dark-700 rounded-sm overflow-hidden">
                                        {(() => {
                                            const currentTaxRate = config.billing?.taxRate || 15;
                                            const total = billingOrder.items.reduce((s, i) => s + (i.price || 0) * i.quantity, 0);
                                            const subtotal = total / (1 + (currentTaxRate / 100));
                                            const tax = total - subtotal;

                                            return (
                                                <table className="w-full text-xs">
                                                    <tbody className="divide-y divide-gray-100 dark:divide-dark-800">
                                                        <tr>
                                                            <td className="px-2 py-1 font-bold bg-gray-50 dark:bg-dark-800">SUBTOTAL 15%</td>
                                                            <td className="px-2 py-1 text-right">${subtotal.toFixed(2)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td className="px-2 py-1 font-bold bg-gray-50 dark:bg-dark-800">SUBTOTAL 0%</td>
                                                            <td className="px-2 py-1 text-right">$0.00</td>
                                                        </tr>
                                                        <tr>
                                                            <td className="px-2 py-1 font-bold bg-gray-50 dark:bg-dark-800">DESCUENTO</td>
                                                            <td className="px-2 py-1 text-right">$0.00</td>
                                                        </tr>
                                                        <tr>
                                                            <td className="px-2 py-1 font-bold bg-gray-50 dark:bg-dark-800">IVA {currentTaxRate}%</td>
                                                            <td className="px-2 py-1 text-right">${tax.toFixed(2)}</td>
                                                        </tr>
                                                        <tr>
                                                            <td className="px-2 py-1 font-bold bg-gray-50 dark:bg-dark-800">PROPINA</td>
                                                            <td className="px-2 py-1 text-right">$0.00</td>
                                                        </tr>
                                                        <tr className="border-t-2 border-gray-300 dark:border-dark-600">
                                                            <td className="px-2 py-1 font-bold bg-gray-100 dark:bg-dark-700 text-sm">VALOR TOTAL</td>
                                                            <td className="px-2 py-1 text-right font-bold text-sm">${total.toFixed(2)}</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            );
                                        })()}
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Right Column: Client Data Form */}
                        <div className="md:w-1/3 space-y-4 border-l dark:border-dark-700 md:pl-6">
                            <h3 className="text-lg font-bold text-gray-900 dark:text-white">Datos del Cliente</h3>

                            {/* Consumidor Final Shortcut */}
                            <button
                                onClick={() => setBillingData({
                                    identification: '9999999999999',
                                    name: 'CONSUMIDOR FINAL',
                                    email: 'consumidor@final.com',
                                    address: 'S/N',
                                    phone: '9999999999',
                                    paymentMethod: '01'
                                })}
                                className="w-full py-1.5 bg-gray-100 hover:bg-gray-200 dark:bg-dark-700 dark:hover:bg-dark-600 text-xs font-semibold text-gray-600 dark:text-gray-300 rounded border border-gray-300 dark:border-dark-600 transition-colors mb-2"
                            >
                                Usar "Consumidor Final"
                            </button>

                            {/* Warning for CF > $50 */}
                            {billingData.identification === '9999999999999' && (billingOrder.items.reduce((s, i) => s + (i.price || 0) * i.quantity, 0) > 50) && (
                                <div className="bg-yellow-50 text-yellow-800 text-xs p-2 rounded border border-yellow-200 mb-3 flex gap-2 items-start">
                                    <span>⚠️</span>
                                    <span>
                                        <strong>Normativa SRI:</strong> Facturas a Consumidor Final no deben superar los $50.00. Se recomienda ingresar datos reales.
                                    </span>
                                </div>
                            )}

                            <div className="space-y-3">
                                <div>
                                    <div className="flex justify-between items-center mb-1">
                                        <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider">RUC/CI</label>
                                        <span className="text-[10px] bg-blue-50 text-blue-600 px-1.5 py-0.5 rounded">
                                            {billingData.identification === '9999999999999' ? 'Consumidor Final' :
                                                billingData.identification.length === 10 ? 'Cédula' :
                                                    billingData.identification.length === 13 ? 'RUC' : 'Pasaporte/Otro'}
                                        </span>
                                    </div>
                                    <input
                                        type="text"
                                        value={billingData.identification}
                                        onChange={e => {
                                            const val = e.target.value.replace(/[^0-9]/g, '');
                                            setBillingData({ ...billingData, identification: val })
                                        }}
                                        maxLength={13}
                                        className={inputClass}
                                        placeholder="0999999999001"
                                        autoFocus
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">CLIENTE</label>
                                    <input
                                        type="text"
                                        value={billingData.name}
                                        onChange={e => setBillingData({ ...billingData, name: e.target.value.toUpperCase() })}
                                        className={inputClass}
                                        placeholder="NOMBRE DEL CLIENTE"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">
                                        Correo Electrónico <span className="text-gray-400 normal-case font-normal">(opcional)</span>
                                    </label>
                                    <input
                                        type="email"
                                        value={billingData.email}
                                        onChange={e => setBillingData({ ...billingData, email: e.target.value })}
                                        className={inputClass}
                                        placeholder="cliente@email.com (puede dejarlo vacío)"
                                    />
                                    <p className="text-[10px] text-gray-400 mt-0.5">💡 Si no ingresa email, podrá imprimir la factura para entregar físicamente.</p>
                                </div>
                                <div>
                                    <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Dirección</label>
                                    <textarea
                                        value={billingData.address}
                                        onChange={e => setBillingData({ ...billingData, address: e.target.value })}
                                        className={inputClass}
                                        rows={2}
                                        placeholder="Dirección del cliente"
                                    />
                                </div>
                                <div className="grid grid-cols-2 gap-3">
                                    <div>
                                        <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Teléfono</label>
                                        <input
                                            type="tel"
                                            value={billingData.phone}
                                            onChange={e => setBillingData({ ...billingData, phone: e.target.value })}
                                            className={inputClass}
                                            placeholder="0999999999"
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Forma Pago</label>
                                        <select
                                            value={billingData.paymentMethod}
                                            onChange={e => setBillingData({ ...billingData, paymentMethod: e.target.value })}
                                            className={inputClass}
                                        >
                                            <option value="01">01 - SIN UTILIZACION DEL SISTEMA FINANCIERO</option>
                                            <option value="20">20 - OTROS CON UTILIZACION DEL SISTEMA FINANCIERO</option>
                                            <option value="19">19 - TARJETA DE CREDITO</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div className="pt-4 flex flex-col gap-2">
                                <button
                                    onClick={handleProcessBilling}
                                    disabled={!billingData.identification || !billingData.name}
                                    className="w-full py-3 bg-blue-600 text-white rounded-xl hover:bg-blue-700 font-bold shadow-lg shadow-blue-500/30 flex justify-center items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    <span>📩</span> Emitir Documento
                                </button>

                                <button
                                    onClick={() => setIsBillingModalOpen(false)}
                                    className="w-full py-2 text-gray-500 hover:text-gray-700 font-medium text-sm"
                                >
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                </Modal>
            )}

            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
                <h1 className="text-3xl font-bold dark:text-light-background">Gestión de Pedidos</h1>

                <div className="flex bg-gray-100 dark:bg-dark-800 p-1 rounded-lg">
                    <button
                        onClick={() => setActiveTab('active')}
                        className={`px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'active' ? 'bg-white dark:bg-dark-600 text-blue-600 dark:text-blue-400 shadow-sm' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700'}`}
                    >
                        En Curso
                    </button>
                    <button
                        onClick={() => setActiveTab('history')}
                        className={`px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'history' ? 'bg-white dark:bg-dark-600 text-blue-600 dark:text-blue-400 shadow-sm' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700'}`}
                    >
                        Historial
                    </button>
                </div>

                <button onClick={() => handleOpenModal(null)} className="flex items-center bg-blue-600 text-white px-3 py-2 text-sm rounded-lg hover:bg-blue-700 transition-colors shadow-sm"><PlusIcon className="w-5 h-5 mr-1" /> Añadir Pedido</button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                {filteredOrders.length === 0 ? (
                    <div className="col-span-full text-center py-12 text-gray-500 dark:text-gray-400">
                        {activeTab === 'active' ? 'No hay pedidos en curso.' : 'No hay historial de pedidos completados.'}
                    </div>
                ) : (
                    filteredOrders
                        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
                        .map(order => (
                            <OrderCard
                                key={order.id}
                                order={order}
                                onEdit={() => handleOpenModal(order)}
                                onDelete={() => handleDeleteOrder(order.id)}
                                onStatusChange={(newStatus) => handleStatusChange(order.id, newStatus)}
                                onBilling={() => handleOpenBilling(order)}
                            />
                        ))
                )}
            </div>
        </div>
    );
};

export default OrderManagement;
